/**
 * Keeps Data's system prompt in one place.
 *
 * Data's prompt is authored in `agent/instructions.md` — the source of truth.
 * Data itself does not read that file: it runs as a self-hosted Letta agent
 * whose memory is a local git repository of markdown, and Letta loads every
 * file under that memory's `system/` directory into the system prompt. This
 * module renders `agent/instructions.md` into that memory's `system/persona.md`,
 * so the agent follows the repository copy.
 *
 * The render is deterministic, so "did the agent's prompt drift from the file?"
 * is a comparison, not a judgement.
 */

/** Where the agent's prompt lives inside its memory repository. */
export const PERSONA_PATH = "system/persona.md";

/** Frontmatter description carried by the rendered persona file. */
export const PERSONA_DESCRIPTION =
  "Who I am, what I value, and how I approach working with people. Seeded from agent/instructions.md in wazootech/data.";

/** Marks the copy as generated, so an agent does not edit it in place. */
const SEED_NOTE =
  "<!-- Generated by scripts/sync-persona.ts from agent/instructions.md in wazootech/data.\n     Edit that file, not this copy, then re-run the script. -->";

/** Renders the agent's `system/persona.md` from the repository's prompt. */
export function renderPersona(instructions: string): string {
  const body = instructions.replace(/\s+$/u, "");
  return `---\ndescription: ${PERSONA_DESCRIPTION}\n---\n${SEED_NOTE}\n\n${body}\n`;
}

/** The memory repository a self-hosted agent keeps, given its id and home. */
export function memoryDirFor(agentId: string, home: string): string {
  return `${home.replace(/\/+$/u, "")}/.letta/lc-local-backend/memfs/${agentId}/memory`;
}

/** True when the rendered file is not already what is on disk. */
export function personaDrifted(current: string | undefined, rendered: string): boolean {
  return current !== rendered;
}
