import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { memoryDirFor, PERSONA_DESCRIPTION, personaDrifted, renderPersona } from "./sync-persona.ts";

describe("renderPersona", () => {
  it("carries frontmatter, the seed note, and the prompt verbatim", () => {
    const rendered = renderPersona("# Data\n\nYou are Data.\n");
    assert.match(rendered, /^---\ndescription: /u);
    assert.match(rendered, /Generated by scripts\/sync-persona\.ts/u);
    assert.match(rendered, /\n\n# Data\n\nYou are Data\.\n$/u);
    assert.ok(rendered.includes(PERSONA_DESCRIPTION));
  });

  it("is stable, so an unchanged prompt is a no-op", () => {
    const prompt = "# Data\n\nYou are Data.\n";
    const once = renderPersona(prompt);
    assert.equal(renderPersona(prompt), once);
    assert.equal(personaDrifted(once, once), false);
  });

  it("normalizes trailing whitespace", () => {
    assert.equal(renderPersona("# Data\n\n\n"), renderPersona("# Data"));
  });
});

describe("memoryDirFor", () => {
  it("resolves the local backend's memory, ignoring a trailing slash", () => {
    assert.equal(
      memoryDirFor("agent-local-1", "/root/"),
      "/root/.letta/lc-local-backend/memfs/agent-local-1/memory",
    );
  });
});
